print("Santi gay")
print("sprimer commit de la rama test1")
print("sEGUNDO commit de la rama test1")

print("tercer commit de la rama main")
print("cuarto commit de la rama main")
print("quinto commit de la rama main")
print("sexto commit de la rama main")
print("sTercer commit de la rama test1")
print("sCuarto commit de la rama test1")
